name: ItemSmelt
main: com.TopicaRP.spenk.ItemSmelt.ItemSmelt
author: Spenk
version: 1.1
commands:
    ismelt:
        description: /ismelt to add an item smelt recipe or for further help.
        usage: /ismelt to add an item smelt recipe or for further help.